
###Route with jwt auth middleware
### GET userID
GET http://localhost:5000/tokenTest
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWQwYmJmOGE0OTQ1NTVlZTE1OGMwMTciLCJ1c2VybmFtZSI6IlZpa3RvciIsImlzQWRtaW4iOnRydWUsImVtYWlsIjoidmljQHRlc3QuY29tIiwiaWF0IjoxNTkxMDA5ODQ3LCJleHAiOjE1OTEwOTYyNDd9.9fSZOO50GBvvC-kugivX9rhWF-YSRW3Ozg0X6f69Z-k



### get orders test with jwt auth middleware
### GET Users Order based on user ID

GET http://localhost:5000/tokenTest/userOrders
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWNiY2QzMTYwYTJjMDUzMjA2NTdhMTgiLCJ1c2VybmFtZSI6IlNrdXJ0IiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTU5MDY2NDQzNCwiZXhwIjoxNTkwNzUwODM0fQ.T9PSv2jAnG__vb4-E_Q88BC4jGrpXviUNHBx0ESIZOc


####

##LOGIN
##Recieve accessToken & refreshToken
POST http://localhost:5000/users/login
Content-Type: application/json

{   
    "username": "Viktor",
    "password": "123"
}

#####

## REFRESH TOKEN
POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWNiY2QzMTYwYTJjMDUzMjA2NTdhMTgiLCJpYXQiOjE1OTA1OTg5MDB9.wJw-_ZN15DyeHdj9BBPpm3JGJ-XQBAlFsFiDL4S3V9I"
}