GET http://localhost:5000/orders/orders

###

POST http://localhost:5000/orders/orders
Content-Type: application/json

{   
    "user_Id": "5ecba898ff4f8a3af0eaf7da",
    "shoppingCart": [],
    "email": "",
    "adress": {},
    "phone": 1,
    "sent": true,
    "payment_method": "swish",
    "total_price": 1
}

###