GET http://localhost:5000/orders
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWNiY2QzMTYwYTJjMDUzMjA2NTdhMTgiLCJ1c2VybmFtZSI6IlNrdXJ0IiwiaXNBZG1pbiI6ZmFsc2UsImVtYWlsIjoidGVzdG1haWxAdGVzdGRvbWFpbi5jb20iLCJpYXQiOjE1OTEzNjUxNDAsImV4cCI6MTU5MTQ1MTU0MH0.IlAHlPgIX88EQoCsTVGdCIBlqP-h2tX1elBBm5bbL0c
###

POST http://localhost:5000/orders
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWNiY2QzMTYwYTJjMDUzMjA2NTdhMTgiLCJ1c2VybmFtZSI6IlNrdXJ0IiwiZW1haWwiOiJ0ZXN0bWFpbEB0ZXN0ZG9tYWluLmNvbSIsImlhdCI6MTU5MDc0MTg2NywiZXhwIjoxNTkwODI4MjY3fQ.OOZB-HoI0TjB4ZIn2xvWac6w0N_k6WsKzijzaX0ojVg

{   
   // "user_Id
    "products": ["5ecce53d823972c10044b197", "5ecd0528bbbbe912a584a6cc"],
    "email": "lis@test.com",
    "adress": [],
    "phone": 12345,
    "sent": false,
    "payment_method": "swish",
    "total_price": 1
}

###

PUT http://localhost:5000/stock/5eccdced52ae746468b66868
Content-Type: application/json

###