GET http://localhost:5000/products/products

###

POST http://localhost:5000/products/products
Content-Type: application/json

{   
    "artist": "Leif",
    "album": "sds",
    "description": "Mr. Tambourine",
    "price": 279,
    "stock_quantity": 7,
    "image": "www",
    "genre": "Blues"
}

###

PUT http://localhost:5000/products/products/5ece3babc7f90af1142c599e
Content-Type: application/json

{
    "artist": "Stevie Wonder",
    "album": "Love",
    "description": "Inresistable",
    "price": 299,
    "stock_quantity": 7,
    "image": "www",
    "genre": "Soul"
}

###

DELETE http://localhost:5000/products/products/ghwdwd

###


// GET/read one specific genre 
GET http://localhost:5000/products/products/Rock

###

//Fake shoppingcart: adds specific product to shoppingCart[]
GET http://localhost:5000/products/cart/5ecbb14151a0903c625703b1



