GET http://localhost:5000/products/products

###

POST http://localhost:5000/products/products
Content-Type: application/json

{   
    "artist": "The Birds",
    "album": "Mr. Tambourine Man",
    "description": "Mr. Tambourine",
    "price": 279,
    "stock_quantity": 7,
    "image": "www",
    "genre": "Blues"
}

###

PUT http://localhost:5000/products/products/5eca7175e5c7e116ccdd9e9b
Content-Type: application/json

{
    "artist": "Bob Dylan",
    "album": "Self Portrait",
    "description": "Great album",
    "price": 299,
    "stock_quantity": 6,
    "image": "www",
    "genre": "Rock"
}

###

DELETE http://localhost:5000/products/products/gh

###


// GET/read one specific genre 
GET http://localhost:5000/products/products/Soul

###

//Fake shoppingcart: adds specific product to shoppingCart[]
GET http://localhost:5000/products/cart/5ecbb14151a0903c625703b1



