
GET http://localhost:5000/uploads/uploads/5ed4c2a812c15a4b0d7ddf67

###

POST http://localhost:5000/uploads/uploads
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="image"; filename="banan.jpeg"
Content-Type: image/jpeg

< ../banan.jpeg
--FormDataRow--
