
GET http://localhost:5000/uploads/uploads/5ed48db0f2b6ed41380a2c70

###

POST http://localhost:5000/uploads/uploads
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="image"; filename="banan.jpeg"
Content-Type: FormData

< ../banan.jpeg
--FormDataRow--
