GET http://localhost:5000/users/users

###

POST http://localhost:5000/users/register
 Content-Type: application/json

 {   
    "username": "Bowie",
    "password": "hi", 
    "email": "adresstest12@test.com",
    "adress": {
        "city": "stan",
        "street": "lurgatan",
        "street_number": "1",
        "postcode": "1337"
    },
    "isAdmin": false
    }


###

POST http://localhost:5000/users/login
Content-Type: application/json

{   
    "username": "Bowie",
    "password": "hi"
}

###

DELETE http://localhost:5000/users/logout

Content-Type: application/json

{
    "username": "Bowie",
    "password": "hi"
}

#####

