GET http://localhost:5000/users/
###
POST http://localhost:5000/users/register
 Content-Type: application/json

 {   
    "username": "Skurt",
    "password": "123", 
    "email": "testmail@testdomain.com",
    "adress": {
        "city": "stan",
        "street": "lurgatan",
        "street_number": "1",
        "postcode": "1337"
    },
    "isAdmin": false
    }

GET http://localhost:5000/users/users

###

POST http://localhost:5000/users/login
Content-Type: application/json

{   
    "username": "Skurt",
    "password": "123"
}

